### ISSUE TITLE
query the spotify api

### ISSUE THREAD

**Issue by jamieRollison** [jamieRollison/musaic#3]
assuming a user has logged in, we need to be able to get the songs they listened to in the last year. Each song should come with when it was played, as well as stats like valence and genre that we can use to determine the happy/sadness of it.

**Comment by anamivp2** [comment]
Retrieved these track attributes to help determine the overall mood of each song:

- valence: Musical positiveness conveyed by a track 0 to 1
- mode: Minor: 0 -> Major: 1
- danceability: how suitable a track is for dancing 
- energy: Perceptual measure of intensity and activity
